sonar.projectKey=kaoutarbouh09_recouvrex-frontend
sonar.organization=kaoutarbouh09

sonar.projectName=Recouvrex Frontend
sonar.projectVersion=1.0

# Sources
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.tsx,**/*.test.ts

# TypeScript
sonar.typescript.tsconfigPath=tsconfig.json

# Encoding
sonar.sourceEncoding=UTF-8
