apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recouvrex
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kaoutarbouh09/recouvrex
    targetRevision: HEAD
    path: helm/recouvrex
    helm:
      releaseName: recouvrex
  destination:
    server: https://kubernetes.default.svc
    namespace: recouvrex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
