apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recouvrex-postgres-pvc
  namespace: recouvrex
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
