sonar.projectKey=KaoutarBouh09_recouvrex-backend
sonar.organization=KaoutarBouh09

sonar.projectName=Recouvrex Backend
sonar.projectVersion=1.0

# Sources
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

# Encoding
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=**/generated/**,**/target/**
