apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.name }}-secret
  labels:
    {{- include "recouvrex.labels" . | nindent 4 }}
    {{- include "recouvrex.selectorLabels" (dict "component" "backend" "Release" .Release) | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.backend.secret.jwtSecret }}
  DB_PASSWORD: {{ .Values.backend.secret.dbPassword }}
  GEMINI_API_KEY: {{ .Values.backend.secret.geminiApiKey | b64enc }}
  TWILIO_ACCOUNT_SID: {{ .Values.backend.secret.twilioAccountSid | b64enc }}
  TWILIO_AUTH_TOKEN: {{ .Values.backend.secret.twilioAuthToken | b64enc }}
  TWILIO_FROM_NUMBER: {{ .Values.backend.secret.twilioFromNumber | b64enc }}
  MAIL_USERNAME: {{ .Values.backend.secret.mailUsername | b64enc }}
  MAIL_PASSWORD: {{ .Values.backend.secret.mailPassword | b64enc }}
  CLOUDINARY_API_SECRET: {{ .Values.backend.secret.cloudinaryApiSecret | b64enc }}
  KEYCLOAK_JWK_URI: {{ .Values.backend.secret.keycloakJwkUri | b64enc }}
