apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.name }}-secret
  labels:
    {{- include "recouvrex.labels" . | nindent 4 }}
    {{- include "recouvrex.selectorLabels" (dict "component" "backend" "Release" .Release) | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.backend.secret.jwtSecret | quote }}
  DB_PASSWORD: {{ .Values.backend.secret.dbPassword | quote }}
  GEMINI_API_KEY: {{ .Values.backend.secret.geminiApiKey | quote }}
  TWILIO_ACCOUNT_SID: {{ .Values.backend.secret.twilioAccountSid | quote }}
  TWILIO_AUTH_TOKEN: {{ .Values.backend.secret.twilioAuthToken | quote }}
  TWILIO_FROM_NUMBER: {{ .Values.backend.secret.twilioFromNumber | quote }}
  MAIL_USERNAME: {{ .Values.backend.secret.mailUsername | quote }}
  MAIL_PASSWORD: {{ .Values.backend.secret.mailPassword | quote }}
  CLOUDINARY_API_SECRET: {{ .Values.backend.secret.cloudinaryApiSecret | quote }}
  KEYCLOAK_JWK_URI: {{ .Values.backend.secret.keycloakJwkUri | quote }}
