apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.frontend.name }}-config
  labels:
    {{- include "recouvrex.labels" . | nindent 4 }}
    {{- include "recouvrex.selectorLabels" (dict "component" "frontend" "Release" .Release) | nindent 4 }}
data:
  BACKEND_HOST: {{ .Values.frontend.env.backendHost | quote }}   # ← ajouter
  BACKEND_PORT: {{ .Values.frontend.env.backendPort | quote }}   # ← ajouter
  VITE_API_BASE_URL: {{ .Values.frontend.env.viteApiBaseUrl | quote }}
  VITE_KEYCLOAK_BASE_URL: {{ .Values.frontend.env.viteKeycloakBaseUrl | quote }}