apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.name }}-secret
  labels:
    {{- include "recouvrex.labels" . | nindent 4 }}
    {{- include "recouvrex.selectorLabels" (dict "component" "postgres" "Release" .Release) | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.secret.password | quote }}
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}